version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - "./app:/app"
    env_file:
      - database.env
    command: /start-reload.sh

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - database.env
    healthcheck:
      test: [ "CMD", "pgadmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "database-data:/var/lib/postgresql/data/"

volumes:
  database-data: