version: "2"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    build: .
    depends_on:
      - postgres
    expose:
      - "80"
    volumes:
      - "./app:/app"
    env_file:
      - database.env
    environment:
      VIRTUAL_HOST: api.shiny-infra.xyz
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: api.shiny-infra.xyz
      LETSENCRYPT_EMAIL: hackathon@dumpsite.xyz

    command: ["wait-for-it", "postgres:5432", "--", "/start-reload.sh"]

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - "database-data:/var/lib/postgresql/data/"

volumes:
  database-data:
  conf:
  vhost:
  html:
  certs:
