version: "3"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  api:
    build: .
    depends_on:
      - postgres
    expose:
      - "80"
    volumes:
      - "./app:/app"
    env_file:
      - database.env
    environment:
      - VIRTUAL_HOST=api.shiny-infra.xyz
      - VIRTUAL_PORT=80
    command: ["wait-for-it", "postgres:5432", "--", "/start-reload.sh"]

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - "database-data:/var/lib/postgresql/data/"

volumes:
  database-data: