version: "3.8"
services:
  api:
    build: .
    env_file:
      - database.env
    ports:
      - "80:80"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - "database-data:/var/lib/postgresql/data/"

volumes:
  database-data: