version: "3"
services:
  api:
    build: .
    ports:
      - "8080:80"
    volumes:
      - "./app:/app"
    env_file:
      - database.env
    command: /start-reload.sh

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - "database-data:/var/lib/postgresql/data/"

volumes:
  database-data: